Feat/sign in
deletosh/msimbo-google-clone pull request #5
Opened 2021-05-25 01:51 UTC by Jasminethecreator

2021-05-25 01:53 UTC, Jasminethecreator commented
Updated content in the about.html file

-Jasmine

2021-05-26 14:26 UTC, deletosh requested changes

2021-05-26 14:26 UTC, deletosh commented on about.html
> +<div> Hello, how are you? </div?>
@Jasminethecreator please fix this tag

2021-05-26 14:27 UTC, Jasminethecreator commented on about.html
> +<div> Hello, how are you? </div?>
Will do, thanks.

2021-06-01 19:14 UTC, closed without merging